baseURL = 'https://kris.engineer/'
languageCode = 'en-us'
title = "Kris's Blog"
theme = 'typo'

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "A simple blog"
# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a Programmer with a variety of interests. I write about software engineering, infrastructure, and other topics that interest me.
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "bluesky"
url = "https://bsky.app/profile/kris.engineer"

[[params.social]]
name = "mastodon"
url = "https://mastodon.social/@interface"

[[params.social]]
name = "github"
url = "https://github.com/0xinterface"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'tokyonight-moon'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
